routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::group(['middleware' => ['web']], function() {
    Route::resource('blog','BlogController');
});
Route::group(['middleware' => ['web']], function() {
    Route::resource('client','ClientController');
});
Route::group(['middleware' => ['web']], function() {
    Route::resource('newclient','NewclientController');
});

app/Blog.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    protected $table ='blog_post';
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use App\Blog;

class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //show Data
        //$blogs = Blog::all();
        //$blogs =DB::table('blog_post')->paginate(5);
       // $blogs = Blog::paginate(5);
        //return view('blog.index',['blogs'=>$blogs]);
        $search = \Request::get('search');
        $blogs = Blog::where('title','like','%'.$search.'%')->orderBy('id')->paginate(6);
        return view('blog.index',['blogs' => $blogs]);
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('blog.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //validation
        $this->validate($request,
            ['title'=>'required',
             'description'=>'required',]);
        //create new data
        $blog = new blog;
        $blog->title=$request->title;
        $blog->description=$request->description;
        $blog->save();
        return redirect()->route('blog.index')->with('alert-success','Data Has Been Save!');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $blog = Blog::findOrFail($id);
        return view('blog.edit',compact('blog'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // validation
        $this->validate($request,[
            'title'=> 'required',
            'description' => 'required',
        ]);

        $blog = Blog::findOrFail($id);
        $blog->title = $request->title;
        $blog->description = $request->description;
        $blog->save();

        return redirect()->route('blog.index')->with('alert-success','Data Hasbeen Saved!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //DELETE DATA
        $blog = Blog::findOrFail($id);
        $blog->delete();
        return redirect()->route('blog.index')->with('alert-success','Data Has Been Deleted!');

    }
}

resources/views/blog/create.blade.php
@extends('master')
@section('content')
    <div class="row">

        <div class="col-md-1-12">
            <h1><canter> New Blog Form</canter></h1>

        </div>
    </div>
    <div class="row">

        <div class="col-md-12" >

            <form class="" action="{{route('blog.store')}}" method="post">
                {{csrf_field()}}
                <table>
                    <th>Name</th>
                <tr><td><div class="form-group{{($errors->Has('title'))?$errors->first('title'):''}}">
                <input type="text" name="title" class="form-control" placeholder="Enter Title here">
                    {!! $errors->first('title','<p class="help-block">:message</p>') !!}
                </div></td></tr>
                    <th>Descripation</th>
                    <tr><td>
                <div class="form-group{{($errors->Has('description'))?$errors->first('description'):''}}">
                    <input type="text" name="description" class="form-control" placeholder="Enter description here">
                    {!! $errors->first('description','<p class="help-block">:message</p>') !!}
                </div>
                            </td></tr>
                    <tr><td>
                <div class="form-group">
                    <input type="submit" class="btn btn-primary" value="save">
                </div>
                    </td></tr>
                    </table>
            </form>
        </div>

    </div>

    @stop

resources/views/blog/edit.blade.php
@extends('master')
@section('content')
    <div class="row">
        <div class="col-md-12">
            <h1>Edit Data</h1>
        </div>
    </div>
    <div class="row">
        <form class="" action="{{route('blog.update',$blog->id)}}" method="post">
            <input name="_method" type="hidden" value="PATCH">
            {{csrf_field()}}
            <div class="form-group{{ ($errors->has('title')) ? $errors->first('title') : '' }}">
                <input type="text" name="title" class="form-control" placeholder="Enter Title Here" value="{{$blog->title}}">
                {!! $errors->first('title','<p class="help-block">:message</p>') !!}
            </div>
            <div class="form-group{{ ($errors->has('description')) ? $errors->first('title') : '' }}">
                <input type="text" name="description" class="form-control" placeholder="Enter Description Here" value="{{$blog->description}}">
                {!! $errors->first('description','<p class="help-block">:message</p>') !!}
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-primary" value="save">
            </div>
        </form>
    </div>
@stop

resources/views/blog/index.blade.php
@extends('master')
@section('content')
    <div class="form-group row add">
        <div class="col-md-6">
            <h1 style="text-align: center">Blog Information</h1>
        </div>
       >
</div>
    <form class="navbar-form navbar-right" role="search">
        <div class="form-group">
            <input type="text" name="search" class="form-control" placeholder="search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
    </form
<div class="row">
    <table class="table table-striped">
<tr>
    <th> No.</th>
    <th> Title</th>
    <th> Description</th>
    <th> Action</th>
</tr>
        <a href="{{(route('blog.create'))}}" class="btn btn-info pull-left">Create New Data</a><br>
        <?php $no=1;?>
        @foreach($blogs as $blog)
            <tr>
                <td>{{$no++}}</td>
                <td>{{$blog->title}}</td>
                <td>{{$blog->description}}</td>
                <td>
                <form class="" action="{{route('blog.destroy',$blog->id)}}" method="post">
                    <input type="hidden" name="_method" value="delete">
                    <input type="hidden" name="_token" value="{{csrf_token()}}">
                    <a href="{{route('blog.edit',$blog->id)}}" class="btn btn-primary">Edit</a>
                    <input type="submit" class="btn btn-danger" onclick="return confirm('Are you sure to delete this data');" name="name" value="delete">



                </form>
                </td>
            </tr>
        @endforeach

    </table>
</div>
{!! $blogs->links() !!}
    @stop