routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::group(['middleware' => ['web']], function() {
    Route::resource('blog','BlogController');
});
Route::group(['middleware' => ['web']], function() {
    Route::resource('client','ClientController');
});
Route::group(['middleware' => ['web']], function() {
    Route::resource('newclient','NewclientController');
});

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    protected $table ='client';
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use App\Client;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *client
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //show Data
        //$clients = Client::all();
        //$clients =DB::table('client')->paginate(5);
        // $clients = Client::paginate(5);
        //return view('client.index',['clients'=>$clients]);
        $search = \Request::get('search');
        $clients = Client::where('clientname','like','%'.$search.'%')->orderBy('id')->paginate(6);
        return view('client.index',['clients' => $clients]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('client.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //validation
        $this->validate($request,[
            'clientname'=>'required',
            'reference'=>'required',
            'organization'=>'required',
            'item'=>'required',
            'order_date'=>'required',
            'renew_date'=>'required',
            'advance'=>'required',
            'dues'=>'required',
            'total'=>'required',
            'email'=>'required',
            'contact'=>'required',
        ]);
        //create new data
        $client = new client;
        $client->clientname=$request->clientname;
        $client->reference=$request->reference;
        $client->organization=$request->organization;
        $client->item=$request->item;
        $client->order_date=$request->order_date;
        $client->renew_date=$request->renew_date;
        $client->advance=$request->advance;
        $client->dues=$request->dues;
        $client->total=$request->total;
        $client->email=$request->email;
        $client->contact=$request->contact;
        $client->save();
        return redirect()->route('client.index')->with('alert-success','Data Has Been Save!');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $client = Client::findOrFail($id);
        return view('client.edit',compact('client'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // validation
        $this->validate($request,[
            'clientname'=>'required',
            'reference'=>'required',
            'organization'=>'required',
            'item'=>'required',
            'order_date'=>'required',
            'renew_date'=>'required',
            'advance'=>'required',
            'dues'=>'required',
            'total'=>'required',
            'email'=>'required',
            'contact'=>'required',
        ]);

        $client = Client::findOrFail($id);
        $client->clientname = $request->clientname;
        $client->reference = $request->reference;
        $client->organization = $request->organization;
        $client->item = $request->item;
        $client->order_date = $request->order_date;
        $client->renew_date = $request->renew_date;
        $client->advance = $request->advance;
        $client->dues = $request->dues;
        $client->total = $request->total;
        $client->email = $request->email;
        $client->contact = $request->contact;
        $client->save();

        return redirect()->route('client.index')->with('alert-success','Data Hasbeen Saved!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //DELETE DATA
        $client = Client::findOrFail($id);
        $client->delete();
        return redirect()->route('client.index')->with('alert-success','Data Has Been Deleted!');

    }
}

resources/views/client/create.blade.php
@extends('master')
@section('content')
    <div class="row">

        <div class="col-md-1-12">
            <h3 style="text-align: center"> Create Form</h3>

        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <form class="" action="{{route('client.store')}}" method="post">
                {{csrf_field()}}
                  <table  >

                      <tr style="text-align: center"><td style="padding-left:350px " >
                        <td> <p>Client Name:</p>
                          <div class="form-group{{($errors->Has('clientname'))?$errors->first('clientname'):''}}">
                              <input type="text" name="clientname" class="form-control" placeholder="Enter clientname here">
                              {!! $errors->first('clientname','<p class="help-block">:message</p>') !!}
                          </div>
                        </td>
                        <td style="padding-left:30px "> <p>Reference:</p>
                          <div class="form-group{{($errors->Has('reference'))?$errors->first('reference'):''}}">
                              <input type="text" name="reference" class="form-control" placeholder="Enter reference here">
                              {!! $errors->first('reference','<p class="help-block">:message</p>') !!}
                          </div>
                        </td>
                      </tr>

                      <tr style="text-align: center"><td style="padding-left:300px " >
                        <td> <p>Organization</p>
                          <div class="form-group{{($errors->Has('organization'))?$errors->first('organization'):''}}">
                             <input type="text" name="organization" class="form-control" placeholder="Enter organization here">
                             {!! $errors->first('organization','<p class="help-block">:message</p>') !!}
                          </div>
                        </td>
                        <td style="padding-left:30px "> <p>Item</p>
                          <div class="form-group{{($errors->Has('item'))?$errors->first('item'):''}}">
                               <input type="text" name="item" class="form-control" placeholder="Enter item here">
                                {!! $errors->first('item','<p class="help-block">:message</p>') !!}
                          </div>

                        </td>
                      </tr>

                      <tr style="text-align: center"><td style="padding-left:300px " >
                         <td>   <p>Order Date</p>
                            <div class="form-group{{($errors->Has('order_date'))?$errors->first('order_date'):''}}">
                              <input type="date" name="order_date" class="form-control" placeholder="Enter order date here">
                              {!! $errors->first('order_date','<p class="help-block">:message</p>') !!}
                            </div>
                         </td>

                          <td style="padding-left:30px "> <p>Renew Date</p>
                            <div class="form-group{{($errors->Has('renew_date'))?$errors->first('renew_date'):''}}">
                               <input type="date" name="renew_date" class="form-control" placeholder="Enter renew date here">
                                {!! $errors->first('renew_date','<p class="help-block">:message</p>') !!}
                            </div>
                         </td>
                      </tr>


                      <tr style="text-align: center"><td style="padding-left:300px " >

                         <td> <p>Advance</p>
                             <div class="form-group{{($errors->Has('advance'))?$errors->first('advance'):''}}">
                                <input type="number" name="advance" class="form-control" placeholder="Enter advance here">
                                 {!! $errors->first('advance','<p class="help-block">:message</p>') !!}
                             </div>
                         </td>


                          <td style="padding-left:30px "> <p>Dues</p>
                             <div class="form-group{{($errors->Has('dues'))?$errors->first('dues'):''}}">
                                 <input type="number" name="dues" class="form-control" placeholder="Enter dues here">
                                  {!! $errors->first('dues','<p class="help-block">:message</p>') !!}
                             </div>

                         </td>
                      </tr>


                      <tr style="text-align: center"><td style="padding-left:300px " >

                         <td> <p>Total</p>
                              <div class="form-group{{($errors->Has('total'))?$errors->first('total'):''}}">
                                  <input type="number" name="total" class="form-control" placeholder="Enter total here">
                                  {!! $errors->first('total','<p class="help-block">:message</p>') !!}
                              </div>
                         </td>

                          <td style="padding-left:30px "> <p>Email</p>
                              <div class="form-group{{($errors->Has('email'))?$errors->first('email'):''}}">
                                   <input type="text" name="email" class="form-control" placeholder="Enter email here">
                                   {!! $errors->first('email','<p class="help-block">:message</p>') !!}
                              </div>
                         </td>
                      </tr>

                      <tr style="text-align: center"><td style="padding-left:300px " >

                          <td> <p>Contact</p>
                               <div class="form-group{{($errors->Has('contact'))?$errors->first('contact'):''}}">
                                   <input type="number" name="contact" class="form-control" placeholder="Enter email here">
                                   {!! $errors->first('contact','<p class="help-block">:message</p>') !!}
                               </div>
                          </td>
                          <td style="padding-left:30px ">
                              <div class="form-group">
                                  <input type="submit" class="btn btn-primary" value="save">
                              </div>
                          </td>
                      </tr>

                      </table>
            </form>
        </div>
    </div>

@stop

resources/views/client/edit.blade.php
@extends('master')
@section('content')
    <div class="row">
        <div class="col-md-12">
            <h3 style="text-align: center">Edit Data</1h>
        </div>
    </div>
    <div class="row">
        <form class="" action="{{route('client.update',$client->id)}}" method="post">
            <input name="_method" type="hidden" value="PATCH">
            {{csrf_field()}}
            <table  >

                <tr style="text-align: center"><td style="padding-left:350px " >
                    <td> <p>Client Name:</p>
                        <div class="form-group{{($errors->Has('clientname'))?$errors->first('clientname'):''}}">
                            <input type="text" name="clientname" class="form-control" placeholder="Enter clientname here" value="{{$client->clientname}}">
                            {!! $errors->first('clientname','<p class="help-block">:message</p>') !!}
                        </div>
                    </td>
                    <td style="padding-left:30px "> <p>Reference:</p>
                        <div class="form-group{{($errors->Has('reference'))?$errors->first('reference'):''}}">
                            <input type="text" name="reference" class="form-control" placeholder="Enter reference here" value="{{$client->reference}}">
                            {!! $errors->first('reference','<p class="help-block">:message</p>') !!}
                        </div>
                    </td>
                </tr>

                <tr style="text-align: center"><td style="padding-left:300px " >
                    <td> <p>Organization</p>
                        <div class="form-group{{($errors->Has('organization'))?$errors->first('organization'):''}}">
                            <input type="text" name="organization" class="form-control" placeholder="Enter organization here" value="{{$client->organization}}">
                            {!! $errors->first('organization','<p class="help-block">:message</p>') !!}
                        </div>
                    </td>
                    <td style="padding-left:30px "> <p>Item</p>
                        <div class="form-group{{($errors->Has('item'))?$errors->first('item'):''}}">
                            <input type="text" name="item" class="form-control" placeholder="Enter item here" value="{{$client->item}}">
                            {!! $errors->first('item','<p class="help-block">:message</p>') !!}
                        </div>

                    </td>
                </tr>

                <tr style="text-align: center"><td style="padding-left:300px " >
                    <td>   <p>Order Date</p>
                        <div class="form-group{{($errors->Has('order_date'))?$errors->first('order_date'):''}}">
                            <input type="date" name="order_date" class="form-control" placeholder="Enter order date here" value="{{$client->order_date}}">
                            {!! $errors->first('order_date','<p class="help-block">:message</p>') !!}
                        </div>
                    </td>

                    <td style="padding-left:30px "> <p>Renew Date</p>
                        <div class="form-group{{($errors->Has('renew_date'))?$errors->first('renew_date'):''}}">
                            <input type="date" name="renew_date" class="form-control" placeholder="Enter renew date here" value="{{$client->renew_date}}">
                            {!! $errors->first('renew_date','<p class="help-block">:message</p>') !!}
                        </div>
                    </td>
                </tr>


                <tr style="text-align: center"><td style="padding-left:300px " >

                    <td> <p>Advance</p>
                        <div class="form-group{{($errors->Has('advance'))?$errors->first('advance'):''}}">
                            <input type="number" name="advance" class="form-control" placeholder="Enter advance here" value="{{$client->advance}}" >
                            {!! $errors->first('advance','<p class="help-block">:message</p>') !!}
                        </div>
                    </td>


                    <td style="padding-left:30px "> <p>Dues</p>
                        <div class="form-group{{($errors->Has('dues'))?$errors->first('dues'):''}}">
                            <input type="number" name="dues" class="form-control" placeholder="Enter dues here" value="{{$client->dues}}">
                            {!! $errors->first('dues','<p class="help-block">:message</p>') !!}
                        </div>

                    </td>
                </tr>


                <tr style="text-align: center"><td style="padding-left:300px " >

                    <td> <p>Total</p>
                        <div class="form-group{{($errors->Has('total'))?$errors->first('total'):''}}">
                            <input type="number" name="total" class="form-control" placeholder="Enter total here" value="{{$client->total}}">
                            {!! $errors->first('total','<p class="help-block">:message</p>') !!}
                        </div>
                    </td>

                    <td style="padding-left:30px "> <p>Email</p>
                        <div class="form-group{{($errors->Has('email'))?$errors->first('email'):''}}">
                            <input type="text" name="email" class="form-control" placeholder="Enter email here" value="{{$client->email}}">
                            {!! $errors->first('email','<p class="help-block">:message</p>') !!}
                        </div>
                    </td>
                </tr>

                <tr style="text-align: center"><td style="padding-left:300px " >

                    <td> <p>Contact</p>
                        <div class="form-group{{($errors->Has('contact'))?$errors->first('contact'):''}}">
                            <input type="number" name="contact" class="form-control" placeholder="Enter email here" value="{{$client->contact}}" >
                            {!! $errors->first('contact','<p class="help-block">:message</p>') !!}
                        </div>
                    </td>
                    <td style="padding-left:30px ">
                        <div class="form-group">
                            <input type="submit" class="btn btn-primary" value="save">
                        </div>
                    </td>
                </tr>

            </table>
        </form>
    </div>
@stop

resources/views/client/index.blade.php
@extends('master')
@section('content')
    <div class="form-group row add">
        <div class="col-md-6">
            <h2 style="padding-left: 200px;">Client Information</h2>

        </div>

    </div>
    <form class="navbar-form navbar-right" role="search">
        <div class="form-group">
            <input type="text" name="search" class="form-control" placeholder="search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
    </form>
    <div class="row">
        <table class="table table-striped">
            <tr>
                <th> No.</th>
                <th> Client Name</th>
                <th> Reference</th>
                <th> Organization</th>
                <th> Item</th>
                <th> Order Date</th>
                <th> Renew Date</th>
                <th> Advance</th>
                <th> Dues</th>
                <th> Total</th>
                <th> Email</th>
                <th> Contact</th>
                <th> Action</th>
            </tr>
            <a href="{{(route('client.create'))}}" class="btn btn-info pull-left">Create New Data</a><br>
            <?php $no=1;?>
            @foreach($clients as $client)
                <tr>
                    <td>{{$no++}}</td>
                    <td>{{$client->clientname}}</td>
                    <td>{{$client->reference}}</td>
                    <td>{{$client->organization}}</td>
                    <td>{{$client->item}}</td>
                    <td>{{$client->order_date}}</td>
                    <td>{{$client->renew_date}}</td>
                    <td>{{$client->advance}}</td>
                    <td>{{$client->dues}}</td>
                    <td>{{$client->total}}</td>
                    <td>{{$client->email}}</td>
                    <td>{{$client->contact}}</td>
                    <td>
                        <form class="" action="{{route('client.destroy',$client->id)}}" method="post">
                            <input type="hidden" name="_method" value="delete">
                            <input type="hidden" name="_token" value="{{csrf_token()}}">
                            <a href="{{route('client.edit',$client->id)}}" class="btn btn-primary">Edit</a>
                            <input type="submit" class="btn btn-danger" onclick="return confirm('Are you sure to delete this data');" name="name" value="delete">



                        </form>
                    </td>
                </tr>
            @endforeach

        </table>
    </div>
      {!! $clients->links() !!}
@stop