routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::group(['middleware' => ['web']], function() {
    Route::resource('blog','BlogController');
});
Route::group(['middleware' => ['web']], function() {
    Route::resource('client','ClientController');
});
Route::group(['middleware' => ['web']], function() {
    Route::resource('newclient','NewclientController');
});

app/Newclient.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Newclient extends Model
{
    protected $table ='newclient';
}

app/Http/Controllers/NewclientController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use App\Newclient;

class NewclientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $search = \Request::get('search');
        $newclients = Newclient::where('clientname','like','%'.$search.'%')->orderBy('id')->paginate(6);
        return view('newclient.index',['newclients' => $newclients]);
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('newclient.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //validation
        $this->validate($request,[
            'clientname'=>'required',
            'reference'=>'required',
            'organization'=>'required',
            'item'=>'required',
            'contact'=>'required',
            'date'=>'required',
            'time'=>'required',
        ]);
        //create new data
        $newclient = new newclient;
        $newclient->clientname=$request->clientname;
        $newclient->reference=$request->reference;
        $newclient->organization=$request->organization;
        $newclient->item=$request->item;
        $newclient->contact=$request->contact;
        $newclient->date=$request->date;
        $newclient->time=$request->time;
        $newclient->save();
        return redirect()->route('newclient.index')->with('alert-success','Data Has Been Save!');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('newclient.show',compact('newclient'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $newclient = Newclient::findOrFail($id);
        return view('newclient.edit',compact('newclient'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //validation
        $this->validate($request,[
            'clientname'=>'required',
            'reference'=>'required',
            'organization'=>'required',
            'item'=>'required',
            'contact'=>'required',
            'date'=>'required',
            'time'=>'required',
        ]);
        //create new data
        $newclient = new newclient;
        $newclient->clientname=$request->clientname;
        $newclient->reference=$request->reference;
        $newclient->organization=$request->organization;
        $newclient->item=$request->item;
        $newclient->contact=$request->contact;
        $newclient->date=$request->date;
        $newclient->time=$request->time;
        $newclient->save();
        return redirect()->route('newclient.index')->with('alert-success','Data Hasbeen Saved!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //DELETE DATA
        $newclient = Newclient::findOrFail($id);
        $newclient->delete();
        return redirect()->route('newclient.index')->with('alert-success','Data Has Been Deleted!');

    }
}

resources/views/newclient/create.blade.php
@extends('master')
@section('content')
    <div class="row">

        <div class="col-md-1-12">
            <h3 style="text-align: center"> Appointment Form</h3>

        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <form class="" action="{{route('newclient.store')}}" method="post">
                {{csrf_field()}}
                  <table  >

                      <tr style="text-align: center"><td style="padding-left:350px " >
                        <td> <p>Client Name:</p>
                          <div class="form-group{{($errors->Has('clientname'))?$errors->first('clientname'):''}}">
                              <input type="text" name="clientname" class="form-control" placeholder="Enter clientname here">
                              {!! $errors->first('clientname','<p class="help-block">:message</p>') !!}
                          </div>
                        </td>
                        <td style="padding-left:30px "> <p>Reference:</p>
                          <div class="form-group{{($errors->Has('reference'))?$errors->first('reference'):''}}">
                              <input type="text" name="reference" class="form-control" placeholder="Enter reference here">
                              {!! $errors->first('reference','<p class="help-block">:message</p>') !!}
                          </div>
                        </td>
                      </tr>

                      <tr style="text-align: center"><td style="padding-left:300px " >
                        <td> <p>Organization</p>
                          <div class="form-group{{($errors->Has('organization'))?$errors->first('organization'):''}}">
                             <input type="text" name="organization" class="form-control" placeholder="Enter organization here">
                             {!! $errors->first('organization','<p class="help-block">:message</p>') !!}
                          </div>
                        </td>
                        <td style="padding-left:30px "> <p>Item</p>
                          <div class="form-group{{($errors->Has('item'))?$errors->first('item'):''}}">
                               <input type="text" name="item" class="form-control" placeholder="Enter item here">
                                {!! $errors->first('item','<p class="help-block">:message</p>') !!}
                          </div>

                        </td>
                      </tr>


                      <tr style="text-align: center"><td style="padding-left:300px " >

                          <td> <p>Contact</p>
                              <div class="form-group{{($errors->Has('contact'))?$errors->first('contact'):''}}">
                                  <input type="number" name="contact" class="form-control" placeholder="Enter contact here">
                                  {!! $errors->first('contact','<p class="help-block">:message</p>') !!}
                              </div>
                          </td>

                          <td> <p>Contact Date</p>
                              <div class="form-group{{($errors->Has('date'))?$errors->first('date'):''}}">
                                  <input type="date" name="date" class="form-control" placeholder="Enter date here">
                                  {!! $errors->first('date','<p class="help-block">:message</p>') !!}
                              </div>
                          </td>
                      </tr>

                      <tr style="text-align: center"><td style="padding-left:300px " >

                          <td> <p>Contact Time</p>
                               <div class="form-group{{($errors->Has('time'))?$errors->first('time'):''}}">
                                   <input type="datetime" name="time" class="form-control" placeholder="Enter time here">
                                   {!! $errors->first('time','<p class="help-block">:message</p>') !!}
                               </div>
                          </td>
                          <td style="padding-left:30px ">
                              <div class="form-group">
                                  <input type="submit" class="btn btn-primary" value="save">
                              </div>
                          </td>
                      </tr>

                      </table>
            </form>
        </div>
    </div>

@stop

resources/views/newclient/edit.blade.php
@extends('master')
@section('content')
    <div class="row">
        <div class="col-md-12">
            <h3 style="text-align: center"> Edit Appointment Data</h3>
        </div>
    </div>
    <div class="row">
        <form class="" action="{{route('newclient.update',$newclient->id)}}" method="post">
            <input name="_method" type="hidden" value="PATCH">
            {{csrf_field()}}
            <table  >

                <tr style="text-align: center"><td style="padding-left:350px " >
                    <td> <p>Client Name:</p>
                        <div class="form-group{{($errors->Has('clientname'))?$errors->first('clientname'):''}}">
                            <input type="text" name="clientname" class="form-control" placeholder="Enter clientname here" value="{{$newclient->clientname}}">
                            {!! $errors->first('clientname','<p class="help-block">:message</p>') !!}
                        </div>
                    </td>
                    <td style="padding-left:30px "> <p>Reference:</p>
                        <div class="form-group{{($errors->Has('reference'))?$errors->first('reference'):''}}">
                            <input type="text" name="reference" class="form-control" placeholder="Enter reference here" value="{{$newclient->reference}}">
                            {!! $errors->first('reference','<p class="help-block">:message</p>') !!}
                        </div>
                    </td>
                </tr>

                <tr style="text-align: center"><td style="padding-left:300px " >
                    <td> <p>Organization</p>
                        <div class="form-group{{($errors->Has('organization'))?$errors->first('organization'):''}}">
                            <input type="text" name="organization" class="form-control" placeholder="Enter organization here" value="{{$newclient->organization}}">
                            {!! $errors->first('organization','<p class="help-block">:message</p>') !!}
                        </div>
                    </td>
                    <td style="padding-left:30px "> <p>Item</p>
                        <div class="form-group{{($errors->Has('item'))?$errors->first('item'):''}}">
                            <input type="text" name="item" class="form-control" placeholder="Enter item here" value="{{$newclient->item}}">
                            {!! $errors->first('item','<p class="help-block">:message</p>') !!}
                        </div>

                    </td>
                </tr>


                <tr style="text-align: center"><td style="padding-left:300px " >


                    <td> <p>Contact</p>
                        <div class="form-group{{($errors->Has('contact'))?$errors->first('contact'):''}}">
                            <input type="number" name="contact" class="form-control" placeholder="Enter email here" value="{{$newclient->contact}}" >
                            {!! $errors->first('contact','<p class="help-block">:message</p>') !!}
                        </div>
                    </td>

                    <td> <p>Contact Date</p>
                        <div class="form-group{{($errors->Has('date'))?$errors->first('date'):''}}">
                            <input type="date" name="date" class="form-control" placeholder="Enter date here" value="{{$newclient->date}}" >
                            {!! $errors->first('date','<p class="help-block">:message</p>') !!}
                        </div>
                    </td>
                </tr>

                <tr style="text-align: center"><td style="padding-left:300px " >

                    <td> <p>Contact Time</p>
                        <div class="form-group{{($errors->Has('time'))?$errors->first('time'):''}}">
                            <input type="datetime" name="time" class="form-control" placeholder="Enter time here" value="{{$newclient->time}}" >
                            {!! $errors->first('time','<p class="help-block">:message</p>') !!}
                        </div>
                    </td>
                    <td style="padding-left:30px ">
                        <div class="form-group">
                            <input type="submit" class="btn btn-primary" value="save">
                        </div>
                    </td>
                </tr>

            </table>
        </form>
    </div>
@stop

resources/views/newclient/index.blade.php
@extends('master')
@section('content')
    <div class="form-group row add">
        <div class="col-md-6">
            <h2 style="text-align: center">Appointment Information</h2>
        </div>
    </div>
    <form class="navbar-form navbar-right" role="search">
        <div class="form-group">
            <input type="text" name="search" class="form-control" placeholder="search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
    </form
    <div class="row">
        <table class="table table-striped">
            <tr>
                <th> No.</th>
                <th> client Name</th>
                <th> Reference</th>
                <th> Organization</th>
                <th> Item</th>
                <th> Contact</th>
                <th> Contact Date</th>
                <th> Contact Time</th>
                <th> Action</th>
            </tr>
            <a href="{{(route('newclient.create'))}}" class="btn btn-info pull-left">New Data</a><br>
            <?php $no=1;?>
            @foreach($newclients as $newclient)
                <tr>
                    <td>{{$no++}}</td>
                    <td>{{$newclient->clientname}}</td>
                    <td>{{$newclient->reference}}</td>
                    <td>{{$newclient->organization}}</td>
                    <td>{{$newclient->item}}</td>
                    <td>{{$newclient->contact}}</td>
                    <td>{{$newclient->date}}</td>
                    <td>{{$newclient->time}}</td>
                    <td>
                        <form class="" action="{{route('newclient.destroy',$newclient->id)}}" method="post">
                            <input type="hidden" name="_method" value="delete">
                            <input type="hidden" name="_token" value="{{csrf_token()}}">
                            <a href="{{route('newclient.edit',$newclient->id)}}" class="btn btn-primary">Edit</a>
                            <input type="submit" class="btn btn-danger" onclick="return confirm('Are you sure to delete this data');" name="name" value="delete">



                        </form>
                    </td>
                </tr>
            @endforeach

        </table>
    </div>
      {!! $newclients->links() !!}
@stop